### PR TITLE
Add ARM64 archictecture (Apple silicon) support

### PR DESCRIPTION
**Pull request by jmgarnier**
Heavily inspired by #17 

Tested successfully on CI ( [Docker image armv7l](https://hub.docker.com/layers/ruby/library/ruby/3.0.2-alpine3.13/images/sha256-57ac5190124f0e637c63c42e8cc82c794e92bedfd494c69523ff71e60458921f?context=explore):
image

and on ARM64 M1 macbooks:
image

And on intel macbooks :)

Dear @grosser could you please release a new gem?

### CODE REVIEW

**Comment by grosser** [comment]
that's exactly the same as #17 ?

**Comment by jmgarnier** [comment]
Not quite, I did not touch `ext/cld/build_aux/config.guess` :

image

**Comment by grosser** [comment]
ah ... did not look at that :D

**Comment by grosser** [comment]
0.10.0

**Comment by jmgarnier** [comment]
thank you!

**Comment by jmgarnier** [comment]
image

# 🚀

**Pull request merged**
