### PR TITLE
compile for aarch64

### PR DESCRIPTION
**Pull request by lizthegrey**

### CODE REVIEW

**Comment by grosser** [comment]
won't this break the old 32 bit build ?

**Comment by jmgarnier** [comment]
Hello @jtoy ,

Thank you @lizthegrey for pushing this PR. I am starting with my macbook M! on a new project using this gem and this PR is very welcomed.

And hello old internet firned @grosser ;)

Any chance this PR gets reviewed and a new release in the next months?

For the time being, I will try to fork it and publish an a gem

**Comment by jmgarnier** [comment]
I guess https://github.com/akihikodaki/cld3-ruby which is based on Compact Language Detector v3 (CLD3) ( https://github.com/google/cld3 ) should work. Maybe this gem could be "archived" ?

**Comment by jmgarnier** [comment]
https://github.com/akihikodaki/cld3-ruby could be used a replacement for this gem I guess

**Comment by grosser** [comment]
released as 0.9.0, lmk if that works

**Comment by lizthegrey** [comment]
Thanks! since I submitted this PR a year ago I have no idea if it's bitrotted but I guess we'll find out!

**Comment by jmgarnier** [comment]
It works like a charm 💐 on Apple silicon. Thank you!

**Comment by jmgarnier** [comment]
But  it failed on CI on https://hub.docker.com/layers/ruby/library/ruby/3.0.2-alpine3.13/images/sha256-57ac5190124f0e637c63c42e8cc82c794e92bedfd494c69523ff71e60458921f?context=explore

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.03:34
    current directory: /app/vendor/bundle/ruby/3.0.0/gems/cld-0.9.0/ext/cld03:34
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/3.0.0 -r03:34
./siteconf20210715-1-ag6k1u.rb extconf.rb
```

Sorry about that, I guess I have broken lots of builds in the 🌍 ... Better to yank & revert, I will move to https://github.com/akihikodaki/cld3-ruby

**Comment by grosser** [comment]
thx, reverted+yanked ... lmt if you have an idea how to make it work for all :)

**Pull request merged**
